---
coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 0.05%
    patch:
      default:
        target: 100%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/*.gen.go"
