# Copyright (c) 2026 John Dewey
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

---
openapi: 3.0.0
info:
  title: Health Check API
  version: 1.0.0
tags:
  - name: health
    x-displayName: Health
    description: Health check endpoints for liveness, readiness, and detailed status.
paths:
  /health:
    get:
      operationId: GetHealth
      summary: Liveness probe
      description: Returns 200 if the process is alive. No checks performed.
      tags:
        - health
      responses:
        '200':
          description: Process is alive.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /health/ready:
    get:
      operationId: GetHealthReady
      summary: Readiness probe
      description: Returns 200 when the service is ready to accept traffic.
      tags:
        - health
      responses:
        '200':
          description: Service is ready.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyResponse'
        '503':
          description: Service is not ready.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyResponse'
  /health/status:
    get:
      operationId: GetHealthStatus
      summary: System status and component health
      description: Returns per-component health status with system metrics. Requires authentication.
      tags:
        - health
      security:
        - BearerAuth:
            - health:read
      responses:
        '200':
          description: All components healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '401':
          description: Unauthorized - API key required.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '503':
          description: One or more components unhealthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status.
          example: "ok"
      required:
        - status

    ReadyResponse:
      type: object
      properties:
        status:
          type: string
          description: Readiness status.
          example: "ready"
        error:
          type: string
          description: Error message when not ready.
      required:
        - status

    ComponentHealth:
      type: object
      properties:
        status:
          type: string
          description: Component health status.
          example: "ok"
        error:
          type: string
          description: Error message when component is unhealthy.
      required:
        - status

    NATSInfo:
      type: object
      properties:
        url:
          type: string
          description: Connected NATS server URL.
          example: "nats://localhost:4222"
        version:
          type: string
          description: NATS server version.
          example: "2.10.0"
      required:
        - url
        - version

    StreamInfo:
      type: object
      properties:
        name:
          type: string
          description: Stream name.
          example: "JOBS"
        messages:
          type: integer
          description: Number of messages in the stream.
          example: 42
        bytes:
          type: integer
          description: Total bytes in the stream.
          example: 1024
        consumers:
          type: integer
          description: Number of consumers on the stream.
          example: 1
      required:
        - name
        - messages
        - bytes
        - consumers

    KVBucketInfo:
      type: object
      properties:
        name:
          type: string
          description: KV bucket name.
          example: "job-queue"
        keys:
          type: integer
          description: Number of keys in the bucket.
          example: 10
        bytes:
          type: integer
          description: Total bytes in the bucket.
          example: 2048
      required:
        - name
        - keys
        - bytes

    JobStats:
      type: object
      properties:
        total:
          type: integer
          description: Total number of jobs.
          example: 100
        unprocessed:
          type: integer
          description: Number of unprocessed jobs.
          example: 5
        processing:
          type: integer
          description: Number of jobs currently processing.
          example: 2
        completed:
          type: integer
          description: Number of completed jobs.
          example: 90
        failed:
          type: integer
          description: Number of failed jobs.
          example: 3
        dlq:
          type: integer
          description: Number of jobs in the dead letter queue.
          example: 0
      required:
        - total
        - unprocessed
        - processing
        - completed
        - failed
        - dlq

    AgentStats:
      type: object
      properties:
        total:
          type: integer
          description: Total number of registered agents.
          example: 5
        ready:
          type: integer
          description: Number of agents with Ready status.
          example: 5
        agents:
          type: array
          items:
            $ref: '#/components/schemas/AgentDetail'
          description: Per-agent registration details.
      required:
        - total
        - ready

    AgentDetail:
      type: object
      properties:
        hostname:
          type: string
          description: Agent hostname.
          example: "web-01"
        labels:
          type: string
          description: Formatted label string.
          example: "group=web.prod"
        registered:
          type: string
          description: Time since last heartbeat registration.
          example: "15s ago"
      required:
        - hostname
        - registered

    ConsumerStats:
      type: object
      properties:
        total:
          type: integer
          description: Total number of JetStream consumers.
          example: 2
        consumers:
          type: array
          items:
            $ref: '#/components/schemas/ConsumerDetail'
          description: Per-consumer details.
      required:
        - total

    ConsumerDetail:
      type: object
      properties:
        name:
          type: string
          description: Consumer name.
          example: "query_any_web_01"
        pending:
          type: integer
          description: Messages not yet delivered.
          example: 0
        ack_pending:
          type: integer
          description: Messages delivered but not yet acknowledged.
          example: 3
        redelivered:
          type: integer
          description: Messages redelivered and not yet acknowledged.
          example: 0
      required:
        - name
        - pending
        - ack_pending
        - redelivered

    StatusResponse:
      type: object
      properties:
        status:
          type: string
          description: Overall health status.
          example: "ok"
        components:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ComponentHealth'
          description: Per-component health status.
        version:
          type: string
          description: Application version.
          example: "0.1.0"
        uptime:
          type: string
          description: Time since server started.
          example: "2h30m"
        nats:
          $ref: '#/components/schemas/NATSInfo'
        streams:
          type: array
          items:
            $ref: '#/components/schemas/StreamInfo'
          description: JetStream stream statistics.
        kv_buckets:
          type: array
          items:
            $ref: '#/components/schemas/KVBucketInfo'
          description: KV bucket statistics.
        jobs:
          $ref: '#/components/schemas/JobStats'
        agents:
          $ref: '#/components/schemas/AgentStats'
        consumers:
          $ref: '#/components/schemas/ConsumerStats'
      required:
        - status
        - components
        - version
        - uptime
