# Copyright (c) 2024 John Dewey
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

---
openapi: 3.0.0
info:
  title: Network Management API
  version: 1.0.0
tags:
  - name: network_operations
    x-displayName: Network
    description: Operations related to the network endpoint.
  - name: dns_operations
    x-displayName: Network/DNS
    description: Operations related to DNS configuration.

paths:
  /network/ping:
    post:
      summary: Ping a remote server
      description: Send a ping to a remote server to verify network connectivity.
      tags:
        - network_operations
      security:
        - BearerAuth:
            - network:write
      parameters:
        - name: target_hostname
          in: query
          required: false
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1
          schema:
            type: string
            default: _any
          description: >
            Target: _any (load-balanced), _all (broadcast), hostname
            (direct), or key:value (label group, e.g., group:web.dev).
      requestBody:
        description: The server to ping.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: The IP address of the server to ping. Supports both IPv4 and IPv6.
                  example: "8.8.8.8"
                  x-oapi-codegen-extra-tags:
                    validate: required,ip
              required:
                - address
      responses:
        '200':
          description: Successful ping response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingCollectionResponse'
        '400':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - API key required
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '500':
          description: Error performing the ping operation.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'

  /network/dns/{interfaceName}:
    get:
      summary: List DNS servers
      description: Retrieve the list of currently configured DNS servers for a specific network interface.
      tags:
        - dns_operations
      operationId: GetNetworkDNSByInterface
      security:
        - BearerAuth:
            - network:read
      parameters:
        - name: interfaceName
          in: path
          required: true
          x-oapi-codegen-extra-tags:
            validate: required,alphanum
          schema:
            type: string
          description: >
            The name of the network interface to retrieve DNS configuration for.
            Must only contain letters and numbers.
        - name: target_hostname
          in: query
          required: false
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1
          schema:
            type: string
            default: _any
          description: >
            Target: _any (load-balanced), _all (broadcast), hostname
            (direct), or key:value (label group, e.g., group:web.dev).

      responses:
        '200':
          description: List of DNS servers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DNSConfigCollectionResponse'
        '400':
          description: Invalid interface name provided.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - API key required
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '500':
          description: Error retrieving DNS servers.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'

  /network/dns:
    put:
      summary: Update DNS servers
      description: Update the system's DNS server configuration.
      tags:
        - dns_operations
      operationId: PutNetworkDNS
      security:
        - BearerAuth:
            - network:write
      parameters:
        - name: target_hostname
          in: query
          required: false
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1
          schema:
            type: string
            default: _any
          description: >
            Target: _any (load-balanced), _all (broadcast), hostname
            (direct), or key:value (label group, e.g., group:web.dev).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DNSConfigUpdateRequest'
      responses:
        '202':
          description: DNS servers update successfully accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DNSUpdateCollectionResponse'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - API key required
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
        '500':
          description: Error updating DNS servers.
          content:
            application/json:
              schema:
                $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'

  # /network/dns/{serverId}:
  #   delete:
  #     summary: Delete a DNS server
  #     description: Remove a specific DNS server from the configuration.
  #     tags:
  #       - dns_operations
  #     operationId: DeleteNetworkDNSServerID
  #     parameters:
  #       - name: serverId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #         description: Identifier of the DNS server to be deleted.
  #     responses:
  #       '204':
  #         description: DNS server deleted successfully.
  #       '404':
  #         description: DNS server not found.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/network.ErrorResponse'
  #       '500':
  #         description: Error deleting DNS server.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/network.ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PingResponse:
      type: object
      properties:
        hostname:
          type: string
          description: The hostname of the worker that executed the ping.
        packets_sent:
          type: integer
          description: Number of packets sent.
          example: 4
        packets_received:
          type: integer
          description: Number of packets received.
          example: 4
        packet_loss:
          type: number
          format: double
          description: Percentage of packet loss.
          example: 0.0
        min_rtt:
          type: string
          description: Minimum round-trip time as a string in Go's time.Duration format.
          example: "14.637103ms"
        avg_rtt:
          type: string
          description: Average round-trip time as a string in Go's time.Duration format.
          example: "18.647498ms"
        max_rtt:
          type: string
          description: Maximum round-trip time as a string in Go's time.Duration format.
          example: "24.309240ms"
        error:
          type: string
          description: Error message if the worker failed to process the request.
      required:
        - hostname

    PingCollectionResponse:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
          description: The job ID used to process this request.
          example: "550e8400-e29b-41d4-a716-446655440000"
        results:
          type: array
          items:
            $ref: '#/components/schemas/PingResponse'
      required:
        - results

    DNSConfigResponse:
      type: object
      properties:
        hostname:
          type: string
          description: The hostname of the worker that served this DNS config.
        servers:
          type: array
          description: List of configured DNS servers.
          items:
            type: string
            description: IPv4 or IPv6 address of the DNS server.
        search_domains:
          type: array
          description: List of search domains.
          items:
            type: string
        error:
          type: string
          description: Error message if the worker failed to process the request.
      required:
        - hostname

    DNSConfigCollectionResponse:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
          description: The job ID used to process this request.
          example: "550e8400-e29b-41d4-a716-446655440000"
        results:
          type: array
          items:
            $ref: '#/components/schemas/DNSConfigResponse'
      required:
        - results

    DNSUpdateResultItem:
      type: object
      properties:
        hostname:
          type: string
        status:
          type: string
          enum: [ok, failed]
        changed:
          type: boolean
          description: Whether the DNS configuration was actually modified.
        error:
          type: string
      required:
        - hostname
        - status

    DNSUpdateCollectionResponse:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
          description: The job ID used to process this request.
          example: "550e8400-e29b-41d4-a716-446655440000"
        results:
          type: array
          items:
            $ref: '#/components/schemas/DNSUpdateResultItem'
      required:
        - results

    DNSConfigUpdateRequest:
      type: object
      properties:
        servers:
          type: array
          x-oapi-codegen-extra-tags:
            validate: required_without=SearchDomains,omitempty,dive,ip,min=1
          description: New list of DNS servers to configure.
          items:
            type: string
            description: IPv4 or IPv6 address of the DNS server.
        search_domains:
          type: array
          x-oapi-codegen-extra-tags:
            validate: required_without=Servers,omitempty,dive,hostname,min=1
          description: New list of search domains to configure.
          items:
            type: string
        interface_name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,alphanum
          description: >
            The name of the network interface to apply DNS configuration to.
            Must only contain letters and numbers.
      required:
        - interface_name

    ErrorResponse:
      $ref: '../../common/gen/api.yaml#/components/schemas/ErrorResponse'
