# Copyright (c) 2026 John Dewey
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

---
openapi: 3.0.0
info:
  title: Command Execution API
  version: 1.0.0
tags:
  - name: command_operations
    x-displayName: Command
    description: Operations related to command execution.

paths:
  /command/exec:
    post:
      summary: Execute a command
      description: >
        Execute a command directly without a shell. This is the safer
        option as it does not interpret shell metacharacters.
      tags:
        - command_operations
      operationId: PostCommandExec
      security:
        - BearerAuth:
            - command:execute
      parameters:
        - name: target_hostname
          in: query
          required: false
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1
          schema:
            type: string
            default: _any
          description: >
            Target: _any (load-balanced), _all (broadcast), hostname
            (direct), or key:value (label group, e.g., group:web.dev).
      requestBody:
        description: The command to execute.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandExecRequest'
      responses:
        '202':
          description: Command execution accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResultCollectionResponse'
        '400':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse
        '401':
          description: Unauthorized - API key required
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse
        '500':
          description: Error executing command.
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse

  /command/shell:
    post:
      summary: Execute a shell command
      description: >
        Execute a command through /bin/sh -c. Supports shell features
        like pipes, redirects, and variable expansion.
      tags:
        - command_operations
      operationId: PostCommandShell
      security:
        - BearerAuth:
            - command:execute
      parameters:
        - name: target_hostname
          in: query
          required: false
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1
          schema:
            type: string
            default: _any
          description: >
            Target: _any (load-balanced), _all (broadcast), hostname
            (direct), or key:value (label group, e.g., group:web.dev).
      requestBody:
        description: The shell command to execute.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandShellRequest'
      responses:
        '202':
          description: Shell command execution accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResultCollectionResponse'
        '400':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse
        '401':
          description: Unauthorized - API key required
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse
        '500':
          description: Error executing shell command.
          content:
            application/json:
              schema:
                $ref: >-
                  ../../common/gen/api.yaml#/components/schemas/ErrorResponse

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CommandExecRequest:
      type: object
      properties:
        command:
          type: string
          description: The executable name or path.
          example: "ls"
          x-oapi-codegen-extra-tags:
            validate: required,min=1
        args:
          type: array
          description: Command arguments.
          items:
            type: string
          example: ["-la", "/tmp"]
        cwd:
          type: string
          description: Working directory for the command.
          example: "/tmp"
        timeout:
          type: integer
          description: Timeout in seconds (default 30, max 300).
          minimum: 1
          maximum: 300
          default: 30
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1,max=300
      required:
        - command

    CommandShellRequest:
      type: object
      properties:
        command:
          type: string
          description: The full shell command string.
          example: "ls -la /tmp | grep log"
          x-oapi-codegen-extra-tags:
            validate: required,min=1
        cwd:
          type: string
          description: Working directory for the command.
          example: "/tmp"
        timeout:
          type: integer
          description: Timeout in seconds (default 30, max 300).
          minimum: 1
          maximum: 300
          default: 30
          x-oapi-codegen-extra-tags:
            validate: omitempty,min=1,max=300
      required:
        - command

    CommandResultItem:
      type: object
      properties:
        hostname:
          type: string
          description: The hostname of the worker that executed the command.
        stdout:
          type: string
          description: Standard output of the command.
        stderr:
          type: string
          description: Standard error output of the command.
        exit_code:
          type: integer
          description: Exit code of the command.
        duration_ms:
          type: integer
          format: int64
          description: Execution time in milliseconds.
        error:
          type: string
          description: >
            Error message if the worker failed to process the request.
      required:
        - hostname

    CommandResultCollectionResponse:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
          description: The job ID used to process this request.
          example: "550e8400-e29b-41d4-a716-446655440000"
        results:
          type: array
          items:
            $ref: '#/components/schemas/CommandResultItem'
      required:
        - results

    ErrorResponse:
      $ref: >-
        ../../common/gen/api.yaml#/components/schemas/ErrorResponse
